# JavaScript Exceptions
- supports exception handling using `try catch` and `throw` syntax
- exceptions can be triggered whenever your code generates exceptions using `throw` or whatever is just generated by the JS runtime
- wrap code in `try` follow the try block with `catch` block
    - if exception is thrown, all code after that is ignored, call stack unwound and catch block is called
- can also specifiy `finally` block it is always called whenever the `try` block is exited regardless of exceptions
- basic syntax
```
try {
  // normal execution code
} catch (err) {
  // exception handling code
} finally {
  // always called code
}
```
- example code
```
function connectDatabase() {
  throw new Error('connection error');
}

try {
  connectDatabase();
  console.log('never executed');
} catch (err) {
  console.log(err);
} finally {
  console.log('always executed');
}

// OUTPUT: Error: connection error
//         always executed
```

## Fallbacks
- fallback pattern
- to implement, put noraml feature in a `try` block and provide a fallback in the `catch`
```
function getScores() {
  try {
    const scores = scoringService.getScores();
    // store the scores so that we can use them later if the network is not available
    window.localStorage.setItem('scores', scores);
    return scores;
  } catch {
    return window.localStorage.getItem('scores');
  }
}
```